#+title: Thesis Planning
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

I know I am not a great writer but I do intend to become better. It is my intention that for the next year as I work on my honours thesis I will continually post my work and progress on this website as a way to keep myself in check and improve my writing. I am not sure how other people go about there research work but for me I think me maintaining this website will be good for me.

* Questions Going Forward
[2022-07-17 Sun]
How should I format my posts?

How many posts should I do a week?

What I am doing my thesis on?

How will I balance work, coursework and relationships?

What should my deadlines be (Gantt chart for thesis)?

What makes for a good thesis?

What are my current ideas for a thesis and what can I acheive in researching these topics?



* How am I feeling about life?
[2022-07-17 Sun]
** General Mood?
I am not feeling over the moon about anything, but I also don't feel particularly bad about anything.
** Something to be excited for?
I am looking forward to balancing work, research and study next semester. I do feel like if I put in the effort I can do something I can be proud of.
